- alias: spicata.99000000.xyz
  link: 

- alias: mint fresh notes
  link: mint-fresh-notes/

- alias: my stories about the town
  link: towns/

- alias: quick start tutorials for me (and you)
  link: tutorials/